src/main/java/me/saukin/entities/Clients.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.saukin.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 *
 * @author admin
 */
@Entity
@Table(name = "clients", catalog = "finalLab", schema = "")
@NamedQueries({
    @NamedQuery(name = "Clients.findAll", query = "SELECT c FROM Clients c")
    , @NamedQuery(name = "Clients.findByEmail", query = "SELECT c FROM Clients c WHERE c.email = :email")
    , @NamedQuery(name = "Clients.findByEmailAndPassword", query = "SELECT c from Clients c WHERE c.email=?1 AND c.password=?2")})

public class Clients implements Serializable {
    
    @Id
    @Size(max = 60)
    @Column(name = "EMAIL")
    private String email;
    @Size(max = 12)
    @Column(name = "PASSWORD")
    private String password;
    @Size(max = 20)
    @Column(name = "FIRSTNAME")
    private String firstname;
    @Size(max = 20)
    @Column(name = "LASTNAME")
    private String lastname;
    @Size(max = 60)
    @Column(name = "ADDRESS")
    private String address;
    @Size(max = 30)
    @Column(name = "CITY")
    private String city;
    @Size(max = 30)
    @Column(name = "PROVINCE")
    private String province;
    @Size(max = 20)
    @Column(name = "COUNTRY")
    private String country;
    @Size(max = 10)
    @Column(name = "POSTALCODE")
    private String postalcode;
    @Size(max = 60)
    @Column(name = "BOOK")
    private String book;

    private static final long serialVersionUID = 1L;

    public Clients() {
    }

    public Clients(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPostalcode() {
        return postalcode;
    }

    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    public String getBook() {
        return book;
    }

    public String setBook(String book) {
        this.book = book;
        return "registration";
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (email != null ? email.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Clients)) {
            return false;
        }
        Clients other = (Clients) object;
        if ((this.email == null && other.email != null) || (this.email != null && !this.email.equals(other.email))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "me.saukin.BackingBean.Clients[ id=" + email + " ]";
    }

    
    
}

src/main/java/me/saukin/BackingBean/DownloadBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.saukin.BackingBean;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;


import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import me.saukin.entities.Clients;
import me.saukin.jpaControllers.ClientsJpaController;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 *
 * @author admin
 */
@Named
@RequestScoped
public class DownloadBean {
     
    @Inject
    private ClientsJpaController clientsJpaController;
    
    @Inject
    private LoginBean loginBean;
    
    
    
    public StreamedContent getDownloadValue() throws Exception {
        
        String userEmail = loginBean.getEmail();
        Clients client = clientsJpaController.findClientByEmail(userEmail);
        String book = client.getBook();
        
        StreamedContent download;
        File file = new File("c:\\Users\\admin\\Documents\\NetBeansProjects\\FinalLab\\src\\main\\webapp\\resources\\files\\" + book + ".zip");
        InputStream input = new FileInputStream(file);
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        download = new DefaultStreamedContent(input, externalContext.getMimeType(file.getName()), file.getName());
        System.out.println("PREP = " + download.getName());
        return download;
    }
    
    
//    StreamedContent file;
//     
//    public DownloadBean() {        
//        InputStream stream = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/images/sherlock.jpg");
//        file = new DefaultStreamedContent(stream, "image/jpg", "downloaded_boromir.jpg");
//    }
// 
//    public StreamedContent getFile() {
//        return file;
//    }
}

src/main/java/me/saukin/BackingBean/LoginBean.java

package me.saukin.BackingBean;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpSession;
import me.saukin.entities.Clients;
import me.saukin.jpaControllers.ClientsJpaController;
import me.saukin.util.MessageUtil;
import org.primefaces.PrimeFaces;

/**
 *
 * @author saukin
 */

@Named
@SessionScoped
public class LoginBean implements Serializable{
    
    @Inject
    RegisterBean registerBean;
    
    @Inject
    private ClientsJpaController clientsJpaController;
    
    @Inject
    private Clients clients;
    
    private String email;
    private String password;
    private String loginMessage = "";

    
    public String getLoginMessage() {
        return loginMessage;
    }

    public void setLoginMessage(String loginMessage) {
        this.loginMessage = loginMessage;
    }
    
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    private FacesMessage message = null;
    private boolean loggedIn = false;
    
    public String login() {
        String s;
        
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().
               getExternalContext().getSession(false);
        Clients cl = clientsJpaController.findClientByEmail(email);
        

        

        if (cl != null) {
            if (email != null && email.equals(cl.getEmail()) && password != null && password.equals(cl.getPassword())) {
                loggedIn = true;
                session.setAttribute("loggedIn", loggedIn);
                System.out.println("return dwnl");
                s = "download";
            } else {
                loggedIn = false;
                session.setAttribute("loggedIn", loggedIn);
                System.out.println("return null");
                loginMessage = "login error. please check email and password!";
                s = "welcome"; 
            }
        } else {
            loginMessage = "login error. please check email and password!";
            s = "welcome";
        }
        return s;
    }   
    
    
    
    
    

    
}

src/main/java/me/saukin/BackingBean/RegisterBean.java

package me.saukin.BackingBean;

import java.io.Serializable;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import me.saukin.entities.Clients;
import me.saukin.jpaControllers.ClientsJpaController;
import me.saukin.util.MessageUtil;

/**
 *
 * @author saukin
 */
@Named("registerBean")
@SessionScoped
public class RegisterBean implements Serializable {
    
    @Inject
    private ClientsJpaController clientsJpaController;
    
    private Clients clients;
    
//    private String book = "";
//
//    public String getBook() {
//        return book;
//    }
//
//    public void setBook(String book) {
//        this.book = book;
//    }
    
    
    
    public Clients getClients() {
        if (clients == null) {
            clients = new Clients();
        }
        return clients;
    }
    
//    public void setClients(Clients clients) {
//        this.clients = clients;
//    }
    
    public boolean isEmailValid() {
        boolean valid = false;
        String email = clients.getEmail();
        if (email != null) {
            if (clientsJpaController.findClientByEmail(email) == null) {
                valid = true;
            } else {
                FacesMessage message = MessageUtil.getMessage("me.saukin.bundles.messages", 
                        "emailExists", null);
                message.setSeverity(FacesMessage.SEVERITY_ERROR);
                FacesContext.getCurrentInstance().addMessage("signupForm:email", message);
            }
        }
        return valid;
    }
    
    
    public String createClients() throws Exception {
        if (isEmailValid()) {
            clientsJpaController.create(clients);
        return "login";
        }
        return null;
    }
    
//    public String chooseBook() {
//        clients.setBook(book);
//        System.out.println("Book is " + clients.getBook());
//        return "registration";
//    }
    
}

src/main/java/me/saukin/jpaControllers/ClientsJpaController.java
package me.saukin.jpaControllers;

import java.io.Serializable;
import java.util.List;
import javax.annotation.Resource;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.NotSupportedException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;
import javax.transaction.UserTransaction;
import me.saukin.entities.Clients;
import me.saukin.jpaControllers.exceptions.NonexistentEntityException;

import me.saukin.jpaControllers.exceptions.RollbackFailureException;

/**
 *
 * @author saukin
 */

@Named
@RequestScoped
public class ClientsJpaController implements Serializable {

    @Resource
    private UserTransaction utx;
    
    @PersistenceContext(unitName = "FinalLabPU")
    private EntityManager em;

    public void create(Clients clients) throws RollbackFailureException, Exception {
        try {
            utx.begin();
            em.persist(clients);
            utx.commit();
        } catch (IllegalStateException | SecurityException | HeuristicMixedException | HeuristicRollbackException | NotSupportedException | RollbackException | SystemException ex) {
            try {
                utx.rollback();
            } catch (IllegalStateException | SecurityException | SystemException re) {
                throw new RollbackFailureException("An error occurred attempting to roll back the transaction.", re);
            }
        } 
    }
    
    
    public List<Clients> findAllClients() {
        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Clients> cq = cb.createQuery(Clients.class);
        Root<Clients> client = cq.from(Clients.class);
        cq.select(client);
        TypedQuery<Clients> query = em.createQuery(cq);

        // Using a named query
//        TypedQuery<Fish> query =  entityManager.createNamedQuery("Fish.findAll", Fish.class);

        // Execute the query
        List<Clients> clients = query.getResultList();

        return clients;
    }

   

    public Clients findClients(String email, String password) {
        TypedQuery<Clients> query = em.createNamedQuery("Clients.findByEmailAndPassword", Clients.class);
        query.setParameter(1, email);
        query.setParameter(2, password);
        List<Clients> clients = query.getResultList();
        if (!clients.isEmpty()) {
            return clients.get(0);
        }
        return null;
    }
    
    public Clients findClientByEmail(String email) {
        TypedQuery<Clients> query = em.createNamedQuery("Clients.findByEmail", Clients.class);
        query.setParameter("email", email);
        List<Clients> clients = query.getResultList();
        if (!clients.isEmpty()) {
            return clients.get(0);
        }
        return null;
    }

    public int getClientsCount() {
        CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            Root<Clients> rt = cq.from(Clients.class);
            cq.select(em.getCriteriaBuilder().count(rt));
            Query q = em.createQuery(cq);
            return ((Long) q.getSingleResult()).intValue();
    } 
  
}

src/main/webapp/clients.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Clients list</title>
    </h:head>
    <h:body>
        <h:form>
            <h:dataTable value="#{clientsJpaController.findAllClients()}" var="clients">
                         <!--columnClasses="fishId,commonName" rowClasses="oddrow,evenrow">-->
                <h:column>
                    <f:facet name="header">#{msgs.email}</f:facet>
                        #{clients.email}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msgs.firstname}</f:facet>
                        #{clients.firstname}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msgs.lastname}</f:facet>
                        #{clients.lastname}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msgs.address}</f:facet>
                        #{clients.address}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msgs.city}</f:facet>
                        #{clients.city}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msgs.province}</f:facet>
                        #{clients.province}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msgs.country}</f:facet>
                        #{clients.country}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msgs.postalcode}</f:facet>
                        #{clients.postalcode}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msgs.book}</f:facet>
                        #{clients.book}
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>

src/main/webapp/download.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        
        <h:outputStylesheet name="css/styles.css" />
        
        <script type="text/javascript">
            //<![CDATA[
            document.getElementById("welcome").onclick = function() {
                window.location.href = "/welcome.faces";
            function start() {
                PF('statusDialog').show();
            } function stop() {
                PF('statusDialog').hide();
                window.location.replace("http://localhost:8080/FinalLab/welcome.xhtml");
            }
            //]]>
            
            };
            
        </script>    


        <p:dialog modal="true" widgetVar="statusDialog" header="Status" draggable="false" closable="false" resizable="false">
            <p:graphicImage name="/images/ajaxloadingbar.gif"/>
        </p:dialog>
        <h:form>   
            <p:commandButton id="welcome" value="DOWNLOAD BOOK" ajax="false">
                <p:fileDownload value="#{downloadBean.downloadValue}" />
            </p:commandButton> 
        </h:form>
        <br/>
        <h:form>
            <p:commandButton value="Go to welcome page" action="welcome"/>
            <br/>
            <p:commandButton value="Go to clients page" action="clients"/>
        </h:form>
        
    </h:body>
</html>

src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>LOGIN PAGE</title>
    </h:head>
    <h:body>
        
        <h:outputStylesheet name="css/styles.css" />
        
        <h:form>        
<!--            <p:growl id="growl" sticky="true" showDetail="true" life="3000" />-->

            <p:panel header="Login">
                <h:panelGrid columns="3" cellpadding="5">
                    <h:outputLabel for="email" value="email" />
                    <p:inputText id="email" value="#{loginBean.email}" required="true" label="username"
                                 requiredMessage="#{msgs.emailPrompt}"/>
                    <p:message for="email" style="color:red"/>
                    <h:outputLabel for="password" value="Password:" />
                    <p:password id="password" value="#{loginBean.password}" required="true" label="password"
                               requiredMessage="#{msgs.passwordPrompt}" />
                    <p:message for="password" style="color:red"/>
                    <h:commandButton value="Login" action="#{loginBean.login()}"/>
                   
                </h:panelGrid>
            </p:panel>

        </h:form>
        
        
<!--        <h:form>
            <h:inputText value="#{loginBean.email}" />
            <h:inputText value="#{loginBean.password}" />
            <h:commandButton value="Log In" action="#{loginBean.login()}"/>

        </h:form>-->
        
    </h:body>
</html>

src/main/webapp/registration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
          
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Welcome</title>
    </h:head>
    <h:body>
     
        <h:outputStylesheet name="css/styles.css" />
        

        <div class="all">
            <h:form id="signupForm" >
                <h:panelGrid columns="2">
                    <p:outputPanel class="primepanel">

                        <h1>#{msgs.registration}</h1>
                        <br/>
                        <h:panelGrid columns="3" cellpadding="0" border="0">

                            <p:outputLabel for="email" value="#{msgs.email}"/>
                            <p:inputText id="email" label="#{msgs.email}"
                                         value="#{registerBean.clients.email}"
                                         maxlength="60" required="true"
                                         requiredMessage="#{msgs.required}"/>
                            <p:message for="email" style="color:red"/>

                            <p:outputLabel for="password" value="#{msgs.password}"/>
                            <p:password id="password" label="#{msgs.password}"
                                        value="#{registerBean.clients.password}" feedback="false"
                                        required="true" maxlength="12" promptLabel="#{msgs.passwordPrompt}"
                                        requiredMessage="#{msgs.required}" match="password2"/>
                            <p:message for="password" style="color:red"/>

                            <p:outputLabel for="password2" value="#{msgs.confirm}"/>
                            <p:password id="password2" label="#{msgs.confirm}"
                                        value="#{registerBean.clients.password}" feedback="false"
                                        required="true" maxlength="12" requiredMessage="#{msgs.required}"/>
                            <p:message for="password2" style="color:red"/>

                            <p:outputLabel for="firstname" value="#{msgs.firstname}"/>
                            <p:inputText id="firstname" label="#{msgs.firstname}"
                                         value="#{registerBean.clients.firstname}" maxlength="20" required="true"
                                         requiredMessage="#{msgs.required}"/>
                            <p:message for="firstname" style="color:red"/>

                            <p:outputLabel for="lastname" value="#{msgs.lastname}"/>
                            <p:inputText id="lastname" label="#{msgs.lastname}"
                                         value="#{registerBean.clients.lastname}"  maxlength="20" required="true"
                                         requiredMessage="#{msgs.required}"/>
                            <p:message for="lastname" style="color:red"/>



                            <p:outputLabel for="address" value="#{msgs.address}"/>
                            <p:inputText id="address" label="#{msgs.address}"
                                         value="#{registerBean.clients.address}" maxlength="60" required="true"
                                         requiredMessage="#{msgs.required}"/>
                            <p:message for="address" style="color:red"/>



                            <p:outputLabel for="city" value="#{msgs.city}"/>
                            <p:inputText id="city" label="#{msgs.city}"
                                         value="#{registerBean.clients.city}" maxlength="30" required="true"
                                         requiredMessage="#{msgs.required}"/>
                            <p:message for="city" style="color:red"/>

                            <p:outputLabel for="province" value="#{msgs.province}"/>
                            <p:inputText id="province" label="#{msgs.province}"
                                         value="#{registerBean.clients.province}" maxlength="30" required="true"
                                         requiredMessage="#{msgs.required}"/>
                            <p:message for="province" style="color:red"/>

                            <p:outputLabel for="country" value="#{msgs.country}"/>
                            <p:inputText id="country" label="#{msgs.country}"
                                         value="#{registerBean.clients.country}" maxlength="20" required="true"
                                         requiredMessage="#{msgs.required}"/>
                            <p:message for="country" style="color:red"/>

                            <p:outputLabel for="postalcode" value="#{msgs.postalcode}"/>
                            <p:inputText id="postalcode" label="#{msgs.postalcode}"
                                         value="#{registerBean.clients.postalcode}" maxlength="10" required="true"
                                         requiredMessage="#{msgs.required}"/>
                            <p:message for="postalcode" style="color:red"/>

                        </h:panelGrid>
                        <p:commandButton id="primebutton" value="#{msgs.register}"
                                         style="display: block;margin: 0 auto;"
                                         action="#{registerBean.createClients()}" ajax="false" />

                    </p:outputPanel>
                </h:panelGrid>

            </h:form>

            <h:form>
                <p:commandButton value="login" action="login" immediate="true" />
            </h:form>
        </div>
        
        
        
        
        
        
        
        
        
<!--        <h:form>
            <h:inputText value="#{registerBean.clients.email}" required="true"
                                     requiredMessage="#{msgs.required}"/>
            <h:inputText value="#{registerBean.clients.password}" />

            <h:commandButton type="submit" value="register" action="#{registerBean.createClients()}"/>
        </h:form>-->
        
    </h:body>
</html>

src/main/webapp/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>

        <h:outputStylesheet name="css/styles.css" />

        <div class="all">
            <h1><h:outputText value="BOOK FOR FREE"/></h1>

            <h3>#{msgs.purpose}</h3>


            <h2>#{msgs.bookPrompt}</h2>

            <h4>#{loginBean.loginMessage}</h4>


            <div id="pictures">
                 <h:form>   
                    <p:growl id="growl" life="2000" />
                    <p:commandLink update="growl" action="#{registerBean.clients.setBook('sherlock')}">
                        <h:graphicImage name="images/sherlock.jpg"/>
                        
                    </p:commandLink>
                    <span>       </span>
                    <p:commandLink update="growl" action="#{registerBean.clients.setBook('alice')}" >
                        <h:graphicImage name="images/alice.jpg"/>
                        
                    </p:commandLink>
                    <span>       </span>
                    <p:commandLink update="growl" action="#{registerBean.clients.setBook('moby')}" >
                        <h:graphicImage name="images/moby.jpg"/>
                        
                    </p:commandLink>
                </h:form>
            </div>     
        </div>
    </h:body>
</html>
        
<!--        <h:form>
            <h:selectOneRadio value = "#{registerBean.clients.book}">
                <div id="sherlock">
                    <h:graphicImage url="/resources/images/sherlock.jpg"/>
                    <f:selectItem itemValue = "sherlock" itemLabel = "Item 1" /> 
                </div>
                <div id="alice">
                    <h:graphicImage url="/resources/images/alice.jpg"/>
                    <f:selectItem itemValue = "alice" itemLabel = "Item 2" />
                </div>
                <div id="moby">
                    <h:graphicImage url="/resources/images/moby.jpg"/>
                    <f:selectItem itemValue = "moby" itemLabel = "Item 2" />
                </div>
            </h:selectOneRadio>
            <h:commandButton value="APPLY" action="#{registerBean.chooseBook()}"/>
        </h:form>-->
        
        
        
        
        
        
        
        
<!--        <h:form>
            <div id="sherlock">
                <h:graphicImage id="Image" url="/resources/images/sherlock.jpg"/>
                <h:selectOneRadio  />
            </div>
        </h:form>
        
        <h:form>    
            <div id="alice">
                <h:graphicImage id="Image" url="/resources/images/alice.jpg"/>
                <h:commandButton value="Alice in Wonderland" action="#{registerBean.createClients()}"/>
            </div>
        </h:form>
        
        <h:form>    
            
                <h:commandButton value="Moby Dick" action="#{registerBean.createClients()}"/>
            </div>
        </h:form>-->
 